### ISSUE TITLE
more detail about requirement?

### ISSUE THREAD

**Issue by hainm** [kmb413/CADRES#1]
https://github.com/kmb413/CADRES/blob/master/BlindDataset_StructurePrediction/methods/README.md
- First, should we really need to list python's builtin module like 'glob', 'argparse'? 
- second, what does RosettaScripts come from?

**Comment by arubenstein** [comment]
I hear the point about the needing to list python's builtin modules -
Kristin, what do you think?

And re RosettaScripts - we should list the commit that we're using, I
think.

**Comment by kmb413** [comment]
agree, both points

On Tue, Jun 21, 2016 at 11:57 AM, Aliza Rubenstein <notifications@github.com
